[package]
name = "rust-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.9.0"
aws-sdk-dynamodb = "0.9.0"
lambda_runtime = "0.5.1"
serde = "1.0.136"
serde_json = "1.0.79"
tokio = "1.17.0"
uuid = { version = "1.0.0-alpha.1", features = ["v4", "serde"] }
